name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
        SSH_HOST2: ${{ vars.VPS_HOST }}
        VPS_HOST: 185.88.154.215
        VPS_USER: root
        VPS_PATH: /home/aminkhalili/public_html/weather.aminkhalili.ir/
      run: |
        echo "VPS Host: $SSH_HOST2"
        rsync -avz --delete -e "ssh -p 49150" ./build/ $VPS_USER@$VPS_HOST:$VPS_PATH

# mkdir -p $HOME/.ssh
# echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
# chmod 600 $HOME/.ssh/id_rsa
# ssh-keyscan -H "$VPS_HOST" >> $HOME/.ssh/known_hosts
# rsync -avz --delete ./build/ $VPS_USER@$VPS_HOST:$VPS_PATH

