name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ vars.VPS_HOST }}
        VPS_USER: ${{ vars.VPS_USER }}
        VPS_PATH: ${{ vars.VPS_PATH }}
        VPS_PORT: 49150
      run: |
        ls -ld /home/runner
        ls -ld /home/runner/.ssh || echo "/home/runner/.ssh does not exist"

        mkdir -p /home/runner/.ssh
        chmod 700 /home/runner/.ssh

        ls -ld /home/runner/.ssh

        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa

        ls -l /home/runner/.ssh/id_rsa

        touch /home/runner/.ssh/known_hosts
        chmod 644 /home/runner/.ssh/known_hosts

        ssh-keyscan -p $VPS_PORT -H "$VPS_HOST" >> /home/runner/.ssh/known_hosts

        rsync -avz --delete -e "ssh -p $VPS_PORT" ./build/ $VPS_USER@$VPS_HOST:$VPS_PATH