name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ vars.VPS_HOST }}
        VPS_USER: ${{ vars.VPS_USER }}
        VPS_PATH: ${{ vars.VPS_PATH }}
      run: |
        sudo echo "VPS Host: $VPS_HOST"
        sudo echo "Home: $HOME"
        sudo echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
        sudo mkdir -p $HOME/.ssh
        sudo echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
        sudo cat $HOME/.ssh/id_rsa
        sudo chmod 600 $HOME/.ssh/id_rsa
        sudo ssh-keyscan -P 49150 -H "$VPS_HOST" >> /root/.ssh/known_hosts
        sudo rsync -avz --delete -e "ssh -p 49150" ./build/ $VPS_USER@$VPS_HOST:$VPS_PATH
